version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: imageservice
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./images:/var/www/html/images
    depends_on:
      - composer

  composer:
    image: composer:latest
    volumes:
      - ./src:/app
    working_dir: /app

