name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    name: PHPUnit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t image-service-app -f docker/php/Dockerfile .

      - name: Run PHPUnit tests
        run: docker run --rm image-service-app composer test
